-- Aliases

minetest.register_alias("adminpick", "maptools:pick_admin")
minetest.register_alias("adminpickaxe", "maptools:pick_admin")
minetest.register_alias("admin_pick", "maptools:pick_admin")
minetest.register_alias("admin_pickaxe", "maptools:pick_admin")
minetest.register_alias("pick_admin", "maptools:pick_admin")
minetest.register_alias("pickaxe_admin", "maptools:pick_admin")
minetest.register_alias("pickadmin", "maptools:pick_admin")
minetest.register_alias("pickaxeadmin", "maptools:pick_admin")
minetest.register_alias("infinitefuel", "maptools:infinitefuel")
minetest.register_alias("infinite_fuel", "maptools:infinitefuel")
minetest.register_alias("ifuel", "maptools:infinitefuel")
minetest.register_alias("superapple", "maptools:superapple")
minetest.register_alias("super_apple", "maptools:superapple")
minetest.register_alias("sapple", "maptools:superapple")
minetest.register_alias("nobuild", "maptools:nobuild")
minetest.register_alias("nointeract", "maptools:nointeract")
minetest.register_alias("damage_1", "maptools:damage_1")
minetest.register_alias("damage_2", "maptools:damage_2")
minetest.register_alias("damage_3", "maptools:damage_3")
minetest.register_alias("damage_4", "maptools:damage_4")
minetest.register_alias("damage_5", "maptools:damage_5")
minetest.register_alias("killblock", "maptools:kill")
minetest.register_alias("kill_block", "maptools:kill")
minetest.register_alias("lightblock", "maptools:lightblock")
minetest.register_alias("light_block", "maptools:lightblock")
minetest.register_alias("lightbulb", "maptools:lightbulb")
minetest.register_alias("light_bulb", "maptools:lightbulb")
minetest.register_alias("playerclip", "maptools:playerclip")
minetest.register_alias("player_clip", "maptools:playerclip")
minetest.register_alias("pclip", "maptools:playerclip")
minetest.register_alias("fullclip", "maptools:fullclip")
minetest.register_alias("full_clip", "maptools:fullclip")
minetest.register_alias("fclip", "maptools:fullclip")

-- For people used to *Radiant :D
minetest.register_alias("weaponclip", "maptools:fullclip")
minetest.register_alias("weapon_clip", "maptools:fullclip")

-- Unbreakable block aliases

minetest.register_alias("stone_u", "maptools:stone")
minetest.register_alias("tree_u", "maptools:tree")
minetest.register_alias("cobble_u", "maptools:cobble")
minetest.register_alias("wood_u", "maptools:wood")
minetest.register_alias("sand_u", "maptools:sand")
minetest.register_alias("gravel_u", "maptools:gravel")
minetest.register_alias("brick_u", "maptools:brick")
minetest.register_alias("dirt_u", "maptools:dirt")
minetest.register_alias("glass_u", "maptools:glass")
minetest.register_alias("sandstone_u", "maptools:sandstone")
minetest.register_alias("desert_stone_u", "maptools:desert_stone")
minetest.register_alias("desertstone_u", "maptools:desert_stone")
minetest.register_alias("desert_sand_u", "maptools:desert_sand")
minetest.register_alias("desertsand_u", "maptools:desert_sand")
minetest.register_alias("leaves_u", "maptools:leaves")
minetest.register_alias("grass_u", "maptools:glass")
minetest.register_alias("fullgrass", "maptools:fullgrass")
minetest.register_alias("fullgrass_u", "maptools:fullgrass")
minetest.register_alias("mossycobble_u", "maptools:mossycobble")
minetest.register_alias("mossy_cobble_u", "maptools:mossycobble")
